version: '3.7'
services:
  mysqlContainer:
    image: mysql:8.0.18
    ports:
      - '3306:3306'
    volumes:
      - db_local:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db_local: